-- BG Tracker Schema Upgrade
-- Safe to run on ANY version of the database. Adds what's missing, skips what exists.
-- This file runs on every startup via start.sh.
--
-- As of 2026-03-08, the initial schema (001_initial_schema.sql) is canonical and
-- includes all tables (vendors, destinations, items, receipts, invoices, purchases,
-- users, audit_log) plus all views and indexes. This file is reserved for future
-- incremental upgrades only.

-- Future schema changes go here. Pattern:
-- DO $$ BEGIN
--   IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='...' AND column_name='...') THEN
--     ALTER TABLE ... ADD COLUMN ...;
--   END IF;
-- END $$;
